defaults:
  - model: gpt2_small # "gpt2_minimal", "gpt2_medium", "gpt2_large", "gpt2_xl"
  - data: exponential-colossal
  - dataset: bassextracted
  - logging: subsequence
  - lr: finetuning
  - _self_

out_dir: 'checkpoints'
eval_interval: 10
eval_iters: 10
eval_only: false  # if True, script exits right after the first eval
always_save_checkpoint: false  # if True, always save a checkpoint after each eval
init_from: 'midi-gpt2-0M-pretraining-2024-06-26-12-00.pt'  # 'scratch' or 'midi-gpt2*'
task: subsequence

optimizer:
  learning_rate: ${lr.learning_rate}
  weight_decay: 0.1
  max_iters: ${data.max_iters} # define max_iters in data but leave the parameter here as well
  beta1: 0.9
  beta2: 0.95
  grad_clip: 1.0  # clip gradients at this value, or disable if == 0.0

ddp:
  backend: 'nccl'  # 'nccl', 'gloo', etc.

system:
  device: 'cuda'  # examples: 'cpu', 'cuda', 'cuda:0', 'cuda:1' etc., or try 'mps' on macbooks
  dtype: 'float16'  # 'float32', 'bfloat16', or 'float16', the latter will auto implement a GradScaler
  compile: true  # use PyTorch 2.0 to compile the model to be faster

model:
  n_layer: 2
  n_embd: 10
  n_head: 1

dataset:
  extra_datasets: []
  augmentation:
    max_pitch_shift: 0
    speed_change_factors: []
logging:
  log_interval: 2
