base_dataset_name: "roszcz/maestro-sustain-v2"
extra_datasets: []
sequence_length: 512
sequence_step: 512
pause_detection_threshold: 4
tokenizer_parameters:
  min_time_unit: 0.01
  n_velocity_bins: 32
name: "basic-no-overlap"
