base_dataset_name: "roszcz/maestro-sustain-v2"
extra_datasets: ["roszcz/giant-midi-sustain-v2", "roszcz/pianofor-ai-sustain-v2"]
sequence_length: 1024
sequence_step: 128
pause_detection_threshold: 4
tokenizer_parameters:
  min_time_unit: 0.01
  n_velocity_bins: 32
augmentation_probability: 0.2
augmentation_repetitions: 5
