base_dataset_name: "roszcz/maestro-sustain-v2"
extra_datasets: ["roszcz/giant-midi-sustain-v2"]
sequence_length: 512
sequence_step: 64
pause_detection_threshold: 4
tokenizer_parameters:
  min_time_unit: 0.01
  n_velocity_bins: 32
name: "giant-mid-coarse"
