decay_lr: true  # whether to decay the learning rate
warmup_iters: 1000  # how many steps to warm up for
lr_decay_iters: ${data.max_iters}  # should be ~= max_iters per Chinchilla
min_lr: 6e-5  # minimum learning rate, should be ~= learning_rate/10 per Chinchilla
